### PR TITLE
Update readme.md

### PR DESCRIPTION
**Pull request by vacekj**
Update snake_case variable names to camelCase.
camelCase is the standard casing used in ECMAScript. Some linters will even warn or throw an error when anything other than camelCase is used (with the exception of SNAKE_CAPITAL_CASE for constants).

### CODE REVIEW

**Comment by jirihradil** [comment]
@vacekj Could you please provide a resource/reference for the ECMAScript camelCase recommendation? I think it's based on a preference.

**Comment by vacekj** [comment]
It is true that there is no explicit recommendation to use camelCase. However, the official [ECMAScript spec](https://tc39.es/ecma262/#sec-object.defineproperties) does use camelCase for all functions and methods exclusively, and PascalCase for class names. It is also a widely-accepted best practice, along with the constants casing.

**Comment by vacekj** [comment]
Further example of constants casing in the spec: https://tc39.es/ecma262/#sec-number.max_safe_integer

**Comment by jirihradil** [comment]
So it's matter of preference. I would mention this in the change you made to not confuse students. They can choose a style they want but then they should keep it. Mixing styles leads to confusion and impairs readability.

Thanks!

**Pull request merged**
